name: money_pulse
description: Personal finance app with ultra-fast entry, clear categories, and visual reports
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  path: ^1.9.1
  fl_chart: ^1.0.0
  share_plus: ^11.0.0
  printing: ^5.14.2
  pdf: ^3.11.3
  flutter_secure_storage: ^9.2.4

  flutter_native_splash: ^2.4.6
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  image_picker_android: ^0.8.13+1
  mime: ^2.0.0
  crypto: ^3.0.6
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo/app_icon.png

flutter:

  uses-material-design: true
  assets:
    - assets/db/schema_v1.sql
    - assets/logo/app_icon.png

flutter_native_splash:
  color: "#ffffff"           
  image: assets/logo/app_icon.png  
  android: true
  ios: true
  web: false

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/logo/app_icon.png"    
#   min_sdk_android: 21
